title: MyAIGuitarBuddy
description: Exploring how AI and guitar can play together
baseurl: "/myaiguitarbuddy" # leave empty unless your site is in a subdirectory
url: "https://jamesdickpro.github.io" # change this to your GitHub Pages URL

# theme: null
remote_theme: "mmistakes/minimal-mistakes"

author:
  name: James
  avatar: "/assets/images/avatar.jpg" # optional, can be removed
  bio: "Learning guitar again with AI as my guide."
  location: Canada

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Optional: social links
social:
  github: jamesdickpro

# Enable breadcrumbs, table of contents, etc.
breadcrumbs: false
toc: true
